-- SQL Reference for inquiries table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    budget TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for all users" ON inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read/delete for all users" ON inquiries FOR ALL USING (true);
